@echo off

setlocal ENABLEDELAYEDEXPANSION

set target_platform=%1
set target_configuration=%2
if "%target_platform%"=="" set target_platform=x64

if /I "%target_platform%" equ "all" (
  if "%target_configuration%"=="" (
    set target_configuration=all
  )
  call %0 x86 !target_configuration!
  call %0 x64 !target_configuration!
  call %0 arm !target_configuration!
  call %0 arm64 !target_configuration!
  goto :eof
)

if /I "%target_configuration%" equ "all" (
  call %0 %target_platform% Debug
  call %0 %target_platform% Release
  goto :eof
)

if "%target_configuration%"=="" (
 set target_configuration=Debug
)

set reference_output=%~p0\_reference\%target_platform%\%target_configuration%
set build_output=%~p0\_build\%target_platform%\%target_configuration%

echo Removing version stamps from %reference_output%\winrt
pushd %reference_output%\winrt
for /r %%i in (*.h) do call :filter_version %%i
popd

echo Removing version stamps from %build_output%\winrt
pushd %build_output%\winrt
for /r %%i in (*.h) do call :filter_version %%i
popd

goto :EOF

:filter_version
copy /y %1 %temp%\filtered.h >nul
findstr /v /c:CPPWINRT_VERSION /c:"was generated by" %temp%\filtered.h > %1
goto :EOF

